[project]
name = "othello-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "plantuml>=0.3.0",
    "six>=1.17.0",
]
